# Numpy et Array

La bibliothèque NumPy (http://www.numpy.org/) permet d’effectuer des calculs numériques avec Python. Elle introduit une gestion facilitée des tableaux de nombres.

Il faut au départ importer le package numpy avec l’instruction suivante :

In [3]:
import numpy as np

Les tableaux - numpy.array()

Les tableaux  peuvent être créés avec numpy.array(). On utilise des crochets pour délimiter les listes d’éléments dans les tableaux.



In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

Accès aux éléments d’un tableau :    [ligne, colonne]

In [52]:
print(a[0,1])

2


La fonction numpy.arange() permet de créer des listes en fonction de certain parametres:  (val départ, val max non atteignable, pas entre chaque valeurs)

In [36]:
m = np.arange(3, 15, 1) 
print(m[11])

14


La fonction numpy.linspace() permet d’obtenir un tableau 1D allant d’une valeur de départ à une valeur de fin avec un nombre donné d’éléments. (val départ, val de fin, nombre de val dans tableau)

In [38]:
np.linspace(0, 50, 10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

Pour toutes les fonctions que propose numpy, vous pouvez consulter la documentation : https://numpy.org/doc/

Le typage faible et dynamique et les limites du language interperté fait de python une solution lente pour traiter les tableaux de grande taille. 
Dans beaucoup de cas, Numpy fournit une interface pour les opérations standard qui n'implique que des données du même type. Par exemple, on peut calculer les inverses de tous les éléments d'un tableau Numpy :

In [42]:
tableau_large = np.random.randint(1, 100, size=10)
print(tableau_large)
tableau_large = 1.0 / tableau_large
print(tableau_large)

[85 83  9 68 18 73 76 91 38 57]
[0.01176471 0.01204819 0.11111111 0.01470588 0.05555556 0.01369863
 0.01315789 0.01098901 0.02631579 0.01754386]


Ex 1 :  théorème des valeurs intermédiaires

1. Rappel
Soit f  une fonction continue définie sur un intervalle I et, a et b deux réels de I.Pour tout réel k compris entre f(a) et f(b), il existe au moins un réel c compris entre a et b tel que f(c)=k.

Soit f une fonction continue et strictement monotone sur un intervalle [a;b].Pour tout nombre k compris entre f(a) et f(b), l'équation f(x)=k admet une unique solution dans l'intervalle [a;b].

2. Application
Nous considérons dans cet exercice la fonction:f définie sur l'intervalle [0;1], par: f(x)=x^3+2x−2
Par la conséquence du théorème des valeurs intermédiaires :  l'équation f(x)=0 admet une unique solution x_0 dans [0;1]
* vérifier continuité et stricte monotonie de f sur [0;1]
* Pour savoir si x0 se trouve dans [0;0,5]ou dans [0,5;1], il faut vérifier si f(0) et f(0,5)  sont de mêmes signes
* proposer un algorithme de recherche pour évaluer x_0 en fonction de $N$, donner par l'utilisateur


In [94]:
i=0
while True:
    
    Tableau_3x3 = np.array([np.random.randint(1, 6, size=3), np.random.randint(1, 6, size=3), np.random.randint(1, 6, size=3)])

    Somme_L1 = Tableau_3x3[0,0] + Tableau_3x3[0,1] + Tableau_3x3[0,2]
    Somme_L2 = Tableau_3x3[1,0] + Tableau_3x3[1,1] + Tableau_3x3[1,2]
    Somme_L3 = Tableau_3x3[2,0] + Tableau_3x3[2,1] + Tableau_3x3[2,2]

    Somme_C1 = Tableau_3x3[0,0] + Tableau_3x3[1,0] + Tableau_3x3[2,0]
    Somme_C2 = Tableau_3x3[0,1] + Tableau_3x3[1,1] + Tableau_3x3[2,1]
    Somme_C3 = Tableau_3x3[0,2] + Tableau_3x3[1,2] + Tableau_3x3[2,2]

    Somme_D1 = Tableau_3x3[0,0] + Tableau_3x3[1,1] + Tableau_3x3[2,2]
    Somme_D2 = Tableau_3x3[0,2] + Tableau_3x3[1,1] + Tableau_3x3[2,0]
    i=i+1
    
    if Somme_L1==Somme_L2 & Somme_L2==Somme_L3 & Somme_L3==Somme_C1 & Somme_C1==Somme_C2 & Somme_C2==Somme_C3 & Somme_C3==Somme_D1 & Somme_D1==Somme_D2:
        break


print(Tableau_3x3)
print(i)



[[4 2 3]
 [2 3 4]
 [3 4 2]]
18981


Ex 2: Carrés magiques
Un carré magique est un tableau carré de taille n×n qui contient tous les entiers de 1 à n*2 et qui vérifie que : la somme de chaque ligne, la somme de chaque colonne, la somme de la diagonale principale et la somme de l’anti-diagonale ont toutes la même valeur.

Pour un carré magique de taille n×n, la valeur de la somme est : S_n=n(n^2+1)/2

1. Définir un tableau pour chacun des exemples 3×3 et 4×4
2. Définir une fonction est_carre_magique(carre)qui teste si un tableaudonné est (ou pas) un carré magique
3. Génèrer de façon aléatoire des carrés contenant les entiers de1 àn2grâce à une fonctioncarre_aleatoire(n). 
4. Définir la probabilité d'obtenir un carrée magique
5. Définir une fonctionaddition_carre(carre,k)qui ajoute un entierkà tous les élé-ments du carré.
